version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: kritohanzo/kittygram_backend
    env_file: .env
    depends_on:
      - db
    command:
      - python manage.py migrate
      - python manage.py collectstatic
      - cp -r /app/collected_static/. /backend_static/static/
    volumes:
      - static:/backend_static
      - media:/app/media
  frontend:
    image: kritohanzo/kittygram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
  gateway:
    image: kritohanzo/kittygram_gateway
    ports:
      - 9000:80
    volumes:
      - static:/staticfiles
      - media:/media
